baseURL: http://arnastria.github.io/
languageCode: en-us
title: Arnastria Site
paginate: 5
theme : "PaperMod"


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true

languages:
  
    en:
        languageName: "English"
        weight: 1
        profileMode:
            enabled: true
            title: Ariq Naufal Satria
            # imageUrl: profile.jpg
            # imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "Information System Graduate | Casually code and reading mangas"
            buttons:
                - name: Blog
                  url: posts
                - name: Portofolio
                  url: portofolio
                - name: Download Resume
                  url: https://drive.google.com/file/d/1Y8GmCL0ifQa_iZw6ICx0e7mSTs_hk8qp/view?usp=sharing
                
        menu:
            main:
                - name: Archive
                  url: archives/
                  weight: 1
                - name: Tags
                  url: tags
                  weight: 2
                - name: Categories
                  url: categories
                  weight: 10
                - name: Series
                  url: series
                  weight: 10
                # - name: NullLink
                #   url: "#"
                # - name: NullLink2
                #   url: "#"
                # - name: NullLink3
                #   url: "#"


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    # env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    # author: Theme PaperMod
    # # author: ["Me", "You"] # multiple authors

    # defaultTheme: auto
    # # disableThemeToggle: true
    # ShowShareButtons: true
    # ShowReadingTime: true
    # # disableSpecial1stPost: true
    # displayFullLangName: true
    # ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    # ShowCodeCopyButtons: true
    # ShowToc: true
    # # comments: false
    images: ["profile.png"]

    # profileMode:
    #     enabled: false
    #     title: PaperMod
    #     imageUrl: "#"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    # homeInfoParams:
    #     Title: "PaperMod"
    #     Content: >
    #         Welcome to demo of hugo's theme PaperMod.
    #         - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
    #         - Do give a 🌟 on Github !
    #         - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
    socialIcons:
        - name: github
          url: "https://github.com/Arnastria"
        - name: Linkedin
          url: "https://www.linkedin.com/in/arnastria/"
        # - name: RsS
        #   url: "index.xml"

    editPost:
        URL: "https://github.com/Arnastria/arnastria-hugo"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true